name: Handle Issue Events

on:
  workflow_dispatch:
  issues:
    types: [opened, edited, closed]

jobs:
  log-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Show Issue Info
        run: |
          echo "Action: ${{ github.event.action }}"
          echo "Title: ${{ github.event.issue.title }}"
          echo "User: ${{ github.event.issue.user.login }}"
